### ISSUE TITLE
Python library that does this

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/spc-parser#1]
Python library that does this
https://github.com/rohanisaac/spc/tree/master/spc

Wikipedia info
https://en.wikipedia.org/wiki/SPC_file_format

**Comment by lpatiny** [comment]
Because it is a binary file you should get inspired by:

https://github.com/cheminfo/netcdfjs

And of course reuse our package ... https://www.npmjs.com/package/iobuffer ;)

**Comment by lpatiny** [comment]
TIFF parser is also reusing iobuffer and could help to get inspired: https://github.com/image-js/tiff

**Comment by targos** [comment]
Here is a reference from the creator of the SPC format:

[pdf-spc-file-format_compress.pdf](https://github.com/cheminfo/spc-parser/files/6789007/pdf-spc-file-format_compress.pdf)
