### ISSUE TITLE
Simplify code ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/spc-parser#10]
https://github.com/cheminfo/spc-parser/blob/7f9a308e70ad60d5d49e7b3ee71cdfb34e7891b3/src/dataBlock.js#L33-L44

The code could be simplified by defining outside the first condition:

`const nbPoints = specter.meta.numberPoints ? specter.meta.numberPoints : flags.numberPoints;`

Using this ternary operator you define once for ever the nbPoints and you then need only one loop

**Comment by YiuBen** [comment]
Resolved in 5f6d3b32a6bb23394c387a253936d91f3e0eb211
