### ISSUE TITLE
Variable should be defined later

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/spc-parser#11]
https://github.com/cheminfo/spc-parser/blob/7f9a308e70ad60d5d49e7b3ee71cdfb34e7891b3/src/dataBlock.js#L7

The `let` should be replaced by `const` and be at line 25, not at the beginning.

**Comment by targos** [comment]
I think the variable should be named `spectrum` ?

**Comment by YiuBen** [comment]
Both issues resolved in 5f6d3b32a6bb23394c387a253936d91f3e0eb211 thank you
