### ISSUE TITLE
Check parser

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/spc-parser#19]
This test is faling:

https://github.com/cheminfo/spc-parser/blob/master/src/__tests__/index.test.js#L30

I have the same file as a Jcamp-DX:

[NDR0002.JDX.zip](https://github.com/cheminfo/spc-parser/files/6919082/NDR0002.JDX.zip)

And the Y values are between 0 and 1.  However I'm not sure the SPC contains the same range of Y but I would expect.

@YiuBen could you try to check if this maxY of 0.25 is really correct ?

**Comment by YiuBen** [comment]
Resolved in 02d5f40
Thank you very much
