### ISSUE TITLE
Migration to typescript

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/spc-parser#21]

**Comment by redhaam** [comment]
Hello @lpatiny , 
There's an issue with backward compatibility with old NodeJS versions like 12.x when specifing `ES2020` as a target within tsconfig, Can we see if it is possible to specify an older version like ES6?

**Comment by redhaam** [comment]
Issue addressed with PR #23

**Comment by stropitek** [comment]
When a concern is raised that is directly related to a PR, please comment in the PR directly rather than in the issue.

**Comment by lpatiny** [comment]
Done
