### ISSUE TITLE
Unused code ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/spc-parser#33]
I think this code is not used:

https://github.com/santimirandarp/spc-parser/blob/8bf7dc0412da6859e268b5fb9ea9c3f3bd6476a3/src/utility.ts#L214-L232

**Comment by santimirandarp** [comment]
That is used in the function just above them, `uvOrIR`, it splits the UV-Vis-IR spectra for either wavelength or wavenumber, unless the numbers are too close in which case it returns `"other"`.

**Comment by lpatiny** [comment]
Ok then it should not be 'export'.

**Comment by targos** [comment]
You have to export functions to unit test them.

**Comment by santimirandarp** [comment]
We thought about asking you a brief question @targos.

Code currently uses classes for most returned objects, like [this one](https://github.com/santimirandarp/spc-parser/blob/8bf7dc0412da6859e268b5fb9ea9c3f3bd6476a3/src/utility.ts#L49), but would it be unnecessary and may be better to use a function returning an object instead?

**Comment by targos** [comment]
I'm fine either way.

**Comment by lpatiny** [comment]
> You have to export functions to unit test them.

In this particular case it is only used in this file (and not tested directly)

**Comment by santimirandarp** [comment]
Yes, as we discussed it was only for documenting it (although the descriptions aren't very good.), but I will remove it.
