### ISSUE TITLE
tsc fails

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/spc-parser#42]
After updating the dependencies (minor updates) I have the following message when trying `npm run tsc`:

```
error TS5110: Option 'module' must be set to 'Node16' when option 'moduleResolution' is set to 'Node16'.
```

@targos what is the correct way to solve this issue ?

Also the CI do not check the types and I don't know why.

https://github.com/cheminfo/spc-parser/actions/runs/6076329391/job/16484132978

@jobo322 we have the same issue in many projects.

**Comment by targos** [comment]
Typescript doesn't follow semver, every minor version has breaking changes. I'm not aware of this one and will read the changelog later today.

**Comment by stropitek** [comment]
> Also the CI do not check the types and I don't know why.

That's because `lint-check-types` is not set to `true` in the workflow's configuration: https://github.com/cheminfo/spc-parser/blob/main/.github/workflows/nodejs.yml

**Comment by targos** [comment]
I have no easy solution for now if we want to keep doing dual-mode (commonjs and esm) packages. I suggest to install `"typescript": "~5.1.6"` for now when you encounter this problem.
