### ISSUE TITLE
No need for Math.floor

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/spc-parser#7]
Bitwise operations are always done on int32 in javascript and always returns an integer.

There is no need for Math.floor in

https://github.com/cheminfo/spc-parser/blob/81a205739cfcd5cf0e96577b56f7b1f35aec5a0f/src/utility.js#L58-L60

**Comment by YiuBen** [comment]
Resolved in https://github.com/cheminfo/spc-parser/commit/a56caa4eb915fed1d4ed137f1c9492de4f128dab
