### ISSUE TITLE
What this copy ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/spc-parser#9]
Not sure why you make a copy of this object ?

https://github.com/cheminfo/spc-parser/blob/7f9a308e70ad60d5d49e7b3ee71cdfb34e7891b3/src/dataBlock.js#L9

It would be very important to do it if you was adding / changing properties but it does not seems to be the case.

You could directly use everywhere mainHeader.

**Comment by YiuBen** [comment]
Resolved in 5f6d3b32a6bb23394c387a253936d91f3e0eb211 thank you
